const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'image-converter-app/src/core/i18n.js');
let content = fs.readFileSync(filePath, 'utf8');

// Each language block follows the exact same structure as es/ko/etc.
const langs = {
zh: `  zh:{
    nav_more_tools:'更多工具',
    nav_short:{'jpg-to-png':'JPG转PNG','png-to-jpg':'PNG转JPG','jpg-to-webp':'JPG转WebP','webp-to-jpg':'WebP转JPG','png-to-webp':'PNG转WebP','webp-to-png':'WebP转PNG','compress':'压缩','resize':'调整大小','jpg-to-pdf':'JPG转PDF','png-to-pdf':'PNG转PDF','gif-to-jpg':'GIF转JPG','gif-to-png':'GIF转PNG','bmp-to-jpg':'BMP转JPG','bmp-to-png':'BMP转PNG','tiff-to-jpg':'TIFF转JPG','jpg-to-gif':'JPG转GIF','png-to-gif':'PNG转GIF','crop':'裁剪','rotate':'旋转','flip':'翻转','grayscale':'灰度','watermark':'水印','round-corners':'圆角','remove-background':'移除背景','heic-to-jpg':'HEIC转JPG','image-to-ico':'图片转ICO','jpg-to-svg':'JPG转SVG','meme-generator':'表情包生成器','blur-face':'模糊人脸','html-to-image':'HTML转图片'},
    footer_copy:'© 2026 RelahConvert. 保留所有权利。',footer_company:'公司',footer_legal:'法律',footer_about:'关于',footer_contact:'联系',footer_privacy:'隐私政策',footer_terms:'使用条款',footer_cookies:'Cookie 政策',
    hero_badge:'✦ 免费 · 无需上传 · 浏览器处理',hero_title_1:'您需要的所有工具',hero_title_2:'集于一处，',hero_title_em:'免费',
    hero_desc:'转换、压缩、调整大小和导出图片。文件不会离开您的设备。',
    card_compress_desc:'缩小 JPG、PNG 和 WebP 文件。',card_resize_desc:'调整 JPG 和 PNG 图片大小。',card_jpg_png_desc:'免费将 JPG 转换为 PNG。',card_png_jpg_desc:'免费将 PNG 转换为 JPG。',card_jpg_webp_desc:'免费将 JPG 转换为 WebP。',card_webp_jpg_desc:'免费将 WebP 转换为 JPG。',card_png_webp_desc:'免费将 PNG 转换为 WebP。',card_webp_png_desc:'免费将 WebP 转换为 PNG。',card_jpg_pdf_desc:'免费将 JPG 转换为 PDF。',card_png_pdf_desc:'免费将 PNG 转换为 PDF。',card_meme_generator_desc:'在线免费制作表情包。',card_blur_face_desc:'免费模糊人脸。自动或手动。',card_jpg_to_pdf_desc:'免费将 JPG 转换为 PDF。',card_png_to_pdf_desc:'免费将 PNG 转换为 PDF。',
    tool_title:{'jpg-to-png':'JPG→PNG 转换器','png-to-jpg':'PNG→JPG 转换器','jpg-to-webp':'JPG→WebP 转换器','webp-to-jpg':'WebP→JPG 转换器','png-to-webp':'PNG→WebP 转换器','webp-to-png':'WebP→PNG 转换器','gif-to-jpg':'GIF→JPG 转换器','gif-to-png':'GIF→PNG 转换器','bmp-to-jpg':'BMP→JPG 转换器','bmp-to-png':'BMP→PNG 转换器','tiff-to-jpg':'TIFF→JPG 转换器','jpg-to-gif':'JPG→GIF 转换器','png-to-gif':'PNG→GIF 转换器'},
    tool_desc:{'jpg-to-png':'免费将 JPG 转换为 PNG。','png-to-jpg':'免费将 PNG 转换为 JPG。','jpg-to-webp':'将 JPG 转换为 WebP。','webp-to-jpg':'免费将 WebP 转换为 JPG。','png-to-webp':'将 PNG 转换为 WebP。','webp-to-png':'将 WebP 转换为 PNG。','gif-to-jpg':'免费将 GIF 转换为 JPG。','gif-to-png':'免费将 GIF 转换为 PNG。','bmp-to-jpg':'免费将 BMP 转换为 JPG。','bmp-to-png':'免费将 BMP 转换为 PNG。','tiff-to-jpg':'免费将 TIFF 转换为 JPG。','jpg-to-gif':'免费将 JPG 转换为 GIF。','png-to-gif':'免费将 PNG 转换为 GIF。'},
    select_images:'选择图片',drop_hint:'或拖放图片',add_more:'添加更多',download:'下载',download_zip:'下载 ZIP',processing:'处理中...',
    warn_wrong_format:'文件已跳过。',warn_unsupported:'不支持的格式。',warn_too_large:'文件太大。',warn_only_jpg_png:'只能调整 JPG 和 PNG 大小。',warn_wrong_fmt_tool:'格式错误！此工具仅接受',warn_files:'个文件。',warn_png_to_jpg:'PNG 文件将保存为 JPG。',warn_wrong_fmt_short:'格式错误。',
    compress_title:'图片',compress_title_em:'压缩',compress_desc:'免费压缩 JPG、PNG 和 WebP。',compress_btn:'压缩图片',compress_btn_loading:'压缩中...',compress_result:'更小了！',compress_result_plural:'张图片已',compress_result_singular:'张图片已',
    resize_title:'图片',resize_title_em:'调整大小',resize_desc:'免费调整 JPG 和 PNG 大小。',resize_btn:'调整大小',resize_btn_loading:'调整中...',resize_options:'选项',resize_by_pixels:'按像素',resize_by_percent:'按百分比',resize_width:'宽度 (px)',resize_height:'高度 (px)',resize_aspect:'保持比例',resize_custom_pct:'自定义 %',resize_of_original:'原始大小的',resize_warn_dims:'请输入宽度或高度。',resize_warn_pct:'请输入百分比。',resize_warn_invalid:'无效的尺寸。',
    convert_btn:'转换图片',convert_btn_loading:'转换中...',convert_output_format:'输出格式',convert_to_jpg:'转换为 JPG',convert_to_png:'转换为 PNG',convert_to_webp:'转换为 WebP',also_convert:'也可转换：',
    pdf_btn:'转换为 PDF',pdf_btn_loading:'转换中...',pdf_options:'PDF 选项',pdf_mode_one:'每张图片一个 PDF',pdf_mode_all:'全部合并为一个 PDF',
    whats_next:'接下来？',next_compress:'压缩',next_resize:'调整大小',next_to_png:'转换为 PNG',next_to_jpg:'转换为 JPG',convert_to_ico:'转换为 ICO',up_to_25_files:'最多 25 个文件',ico_sizes_label:'ICO 尺寸（选择需要的）',svg_notice:'此工具将图片嵌入 SVG 容器——使其可无限缩放。如需完整矢量化，请使用 Inkscape。',next_to_webp:'转换为 WebP',next_to_pdf:'转换为 PDF',
    hti_desc:'将任何网站捕获为图片。输入 URL 并下载截图。',hti_url_label:'网站 URL',hti_screen_size:'屏幕大小',hti_format:'格式',hti_btn:'截取屏幕',hti_loading:'捕获中…',hti_download:'下载截图',hti_error:'捕获失败。请检查 URL 后重试。',hti_url_error:'请输入 URL。',hti_mobile:'手机',hti_tablet:'平板',hti_desktop:'桌面',hti_fullhd:'Full HD',
    filter:{all:'全部',optimize:'优化',edit:'编辑',convert:'转换',create:'创建',privacy:'隐私'},
    round_corners_title_1:'图片',round_corners_title_em:'圆角',round_corners_btn:'圆角处理',round_corners_panel:'圆角半径',round_corners_preset_slight:'轻微',round_corners_preset_rounded:'圆角',round_corners_preset_very:'大圆角',round_corners_preset_circle:'圆形',
    meme_generator_title:'表情包生成器',meme_generator_desc:'在线制作表情包。选择模板或上传图片。隐私安全——在浏览器中处理。',meme_generator_upload_btn:'上传图片',meme_generator_template_btn:'选择模板',meme_generator_add_text_btn:'添加文字',meme_generator_add_image_btn:'添加图片',meme_generator_download_btn:'下载表情包',meme_generator_text_inside:'文字在内',meme_generator_text_outside:'文字在外',meme_generator_band_color:'色带颜色',meme_generator_top_text:'顶部文字',meme_generator_bottom_text:'底部文字（可选）',
    meme_title:'表情包',meme_title_em:'生成器',meme_sub:'在线制作表情包。选择模板或上传图片。隐私安全——在浏览器中处理。',meme_upload_btn:'上传图片',meme_template_btn:'选择模板',meme_editor:'表情包编辑器',meme_text_inside:'文字在内',meme_text_outside:'文字在外',meme_band_color:'色带颜色：',meme_top_text:'顶部文字（可选）',meme_bottom_text:'底部文字（可选）',meme_add_text:'添加文字',meme_add_image:'添加图片',meme_download:'下载表情包',meme_choose_templ:'选择表情包模板',
    blur_face_title:'模糊',blur_face_title_em:'人脸',blur_face_sub:'模糊照片中的人脸。自动或手动检测。最多 25 张图片。隐私安全——在浏览器中处理。',blur_face_upload:'上传图片',blur_face_download:'下载图片',blur_face_amount:'模糊程度',blur_face_detecting:'检测人脸中…',blur_face_none:'未检测到人脸。请尝试更清晰的照片或使用手动模糊。',blur_face_found:'个人脸已检测',blur_face_manual:'添加模糊',blur_face_auto:'自动检测',blur_face_mode:'模式',blur_face_select_mode:'选择模式以开始。',blur_face_draw:'在图片上点击并拖动以模糊区域。',blur_face_editor:'模糊编辑器',blur_face_regions:'模糊区域',blur_face_download_zip:'下载全部为 ZIP',blur_face_reset:'上传新图片',blur_face_images_label:'图片',blur_face_drop:'拖放图片到此处或点击上传',blur_face_drop_sub:'JPG、PNG、WebP · 最多 25 张 · 最大 200 MB',blur_face_processing:'处理中',blur_face_creating_zip:'创建 ZIP 中…',blur_face_batch_failed:'批量下载失败',
    seo_faq_title:'常见问题',seo_also_try:'也试试',
    seo:{
      'jpg-to-png':{h2a:'免费将 JPG 转 PNG',steps:['<strong>选择 JPG</strong>。','<strong>转换</strong>。','<strong>下载 PNG</strong>。'],h2b:"免费 JPG→PNG",body:"<p>浏览器中转换。</p>",h3why:'为什么？',why:"PNG 支持透明。",faqs:[{q:'保存文件？',a:'不会。'}],links:[{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/compress',label:'压缩'},{href:'/gif-to-png',label:'GIF→PNG'},{href:'/resize',label:'调整大小'}]},
      'png-to-jpg':{h2a:'免费将 PNG 转 JPG',steps:['<strong>选择 PNG</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 PNG→JPG",body:"<p>浏览器中转换。</p>",h3why:'为什么？',why:"小 60–80%。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'压缩'},{href:'/bmp-to-jpg',label:'BMP→JPG'},{href:'/resize',label:'调整大小'}]},
      'jpg-to-webp':{h2a:'JPG 转 WebP',steps:['<strong>JPG</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 JPG→WebP",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"小 25–35%。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/webp-to-jpg',label:'WebP→JPG'},{href:'/compress',label:'压缩'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'调整大小'}]},
      'webp-to-jpg':{h2a:'WebP 转 JPG',steps:['<strong>WebP</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 WebP→JPG",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"到处可打开。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/jpg-to-webp',label:'JPG→WebP'},{href:'/compress',label:'压缩'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'调整大小'}]},
      'png-to-webp':{h2a:'PNG 转 WebP',steps:['<strong>PNG</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 PNG→WebP",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"小 30–50%。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/webp-to-png',label:'WebP→PNG'},{href:'/compress',label:'压缩'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'调整大小'}]},
      'webp-to-png':{h2a:'WebP 转 PNG',steps:['<strong>WebP</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 WebP→PNG",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"兼容所有编辑器。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/png-to-webp',label:'PNG→WebP'},{href:'/compress',label:'压缩'},{href:'/webp-to-jpg',label:'WebP→JPG'},{href:'/resize',label:'调整大小'}]},
      'gif-to-jpg':{h2a:'GIF 转 JPG',steps:['<strong>GIF</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 GIF→JPG",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"小 60–80%。",faqs:[{q:'动画？',a:'仅第一帧。'},{q:'保存？',a:'不会。'}],links:[{href:'/gif-to-png',label:'GIF→PNG'},{href:'/compress',label:'压缩'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'调整大小'}]},
      'gif-to-png':{h2a:'GIF 转 PNG',steps:['<strong>GIF</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 GIF→PNG",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"百万色彩。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/gif-to-jpg',label:'GIF→JPG'},{href:'/compress',label:'压缩'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'调整大小'}]},
      'bmp-to-jpg':{h2a:'BMP 转 JPG',steps:['<strong>BMP</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 BMP→JPG",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"BMP 大 10–20 倍。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/bmp-to-png',label:'BMP→PNG'},{href:'/compress',label:'压缩'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'调整大小'}]},
      'bmp-to-png':{h2a:'BMP 转 PNG',steps:['<strong>BMP</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 BMP→PNG",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"小 60–80%。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/bmp-to-jpg',label:'BMP→JPG'},{href:'/compress',label:'压缩'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'调整大小'}]},
      'tiff-to-jpg':{h2a:'TIFF 转 JPG',steps:['<strong>TIFF</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 TIFF→JPG",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"小 90–95%。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'压缩'},{href:'/bmp-to-jpg',label:'BMP→JPG'},{href:'/resize',label:'调整大小'}]},
      'jpg-to-gif':{h2a:'JPG 转 GIF',steps:['<strong>JPG</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 JPG→GIF",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"全平台兼容。",faqs:[{q:'动画？',a:'不是。'},{q:'保存？',a:'不会。'}],links:[{href:'/png-to-gif',label:'PNG→GIF'},{href:'/gif-to-jpg',label:'GIF→JPG'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'压缩'}]},
      'png-to-gif':{h2a:'PNG 转 GIF',steps:['<strong>PNG</strong>。','<strong>转换</strong>。','<strong>下载</strong>。'],h2b:"免费 PNG→GIF",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"通用兼容。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/jpg-to-gif',label:'JPG→GIF'},{href:'/gif-to-png',label:'GIF→PNG'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/compress',label:'压缩'}]},
      'crop':{h2a:'无需上传裁剪',steps:['<strong>图片</strong>。','<strong>裁剪</strong>。','<strong>下载</strong>。'],h2b:"免费裁剪",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"去除不需要的部分。",faqs:[{q:'精确尺寸？',a:'是。'},{q:'质量？',a:'无损。'},{q:'保存？',a:'不会。'}],links:[{href:'/resize',label:'调整大小'},{href:'/rotate',label:'旋转'},{href:'/compress',label:'压缩'},{href:'/flip',label:'翻转'}]},
      'rotate':{h2a:'无需上传旋转',steps:['<strong>图片</strong>。','<strong>旋转</strong>。','<strong>下载</strong>。'],h2b:"免费旋转",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"修正方向。",faqs:[{q:'角度？',a:'自由。'},{q:'质量？',a:'无损。'},{q:'保存？',a:'不会。'}],links:[{href:'/crop',label:'裁剪'},{href:'/flip',label:'翻转'},{href:'/resize',label:'调整大小'},{href:'/compress',label:'压缩'}]},
      'flip':{h2a:'无需上传翻转',steps:['<strong>图片</strong>。','<strong>方向</strong>。','<strong>下载</strong>。'],h2b:"免费翻转",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"镜像效果。",faqs:[{q:'区别？',a:'镜像 vs 角度。'},{q:'透明？',a:'保留。'},{q:'保存？',a:'不会。'}],links:[{href:'/rotate',label:'旋转'},{href:'/crop',label:'裁剪'},{href:'/resize',label:'调整大小'},{href:'/compress',label:'压缩'}]},
      'grayscale':{h2a:'转为黑白',steps:['<strong>图片</strong>——最多 25 张。','<strong>预览</strong>。','<strong>下载</strong>。'],h2b:"免费黑白",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"经典美感。",faqs:[{q:'多张？',a:'是——25。'},{q:'质量？',a:'无损。'},{q:'保存？',a:'不会。'}],links:[{href:'/compress',label:'压缩'},{href:'/watermark',label:'水印'},{href:'/rotate',label:'旋转'},{href:'/resize',label:'调整大小'}]},
      'watermark':{h2a:'添加水印',steps:['<strong>图片</strong>——最多 25 张。','<strong>图层</strong>。','<strong>下载</strong>。'],h2b:"免费水印",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"保护照片。",faqs:[{q:'Logo？',a:'是。'},{q:'多个？',a:'是。'},{q:'保存？',a:'不会。'}],links:[{href:'/compress',label:'压缩'},{href:'/resize',label:'调整大小'},{href:'/crop',label:'裁剪'},{href:'/rotate',label:'旋转'}]},
      'remove-background':{h2a:'移除背景',steps:['<strong>图片</strong>。','<strong>AI 移除</strong>。','<strong>PNG</strong>。'],h2b:"免费移除背景",body:"<p>浏览器 AI。</p>",h3why:'为什么？',why:"放置在任何背景上。",faqs:[{q:'保存？',a:'不会。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'压缩'},{href:'/resize',label:'调整大小'},{href:'/crop',label:'裁剪'}]},
      'heic-to-jpg':{h2a:'HEIC 转 JPG',steps:['<strong>HEIC</strong>。','<strong>转换</strong>。','<strong>JPG</strong>。'],h2b:"免费 HEIC→JPG",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"JPG 兼容性高。HEIC 在 Windows 上无法打开。",faqs:[{q:'多张？',a:'是。'},{q:'保存？',a:'不会。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'压缩'},{href:'/resize',label:'调整大小'},{href:'/jpg-to-webp',label:'JPG→WebP'}]},
      'image-to-ico':{h2a:'转为 ICO',steps:['<strong>图片</strong>。','<strong>尺寸</strong>。','<strong>ICO</strong>。'],h2b:"免费 ICO 转换",body:"<p>浏览器中。</p>",h3why:'为什么？',why:"网站图标和 Windows 图标。",faqs:[{q:'多尺寸？',a:'是。'},{q:'保存？',a:'不会。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'调整大小'},{href:'/compress',label:'压缩'},{href:'/crop',label:'裁剪'}]},
      'round-corners':{h2a:'免费圆角处理',steps:['<strong>图片</strong>。','<strong>半径</strong>。','<strong>圆角</strong>。','<strong>PNG</strong>。'],h2b:'免费圆角',body:'<p>浏览器中。</p>',h3why:'为什么？',why:'现代外观。',faqs:[{q:'格式？',a:'PNG。'},{q:'多张？',a:'是——25。'},{q:'上传？',a:'不会。'},{q:'圆形？',a:'是——50%。'},{q:'调节？',a:'0–50%。'}],links:[{href:'/crop',label:'裁剪'},{href:'/resize',label:'调整大小'},{href:'/rotate',label:'旋转'},{href:'/compress',label:'压缩'},{href:'/remove-background',label:'移除背景'},{href:'/jpg-to-png',label:'JPG→PNG'}]},
      'meme-generator':{h2a:'免费制作表情包',steps:['上传或模板。','文字。','样式。','下载。'],h2b:"免费表情包生成器",body:'浏览器中制作表情包。',h3why:'为什么？',why:'最快的分享方式。',faqs:[{q:'上传？',a:'不会。'},{q:'自己的图？',a:'是。'},{q:'水印？',a:'没有。'},{q:'多文字？',a:'是。'},{q:'字体？',a:'Impact, Arial Black, Arial, Verdana, Times New Roman, Georgia, Courier New, Comic Sans。'},{q:'PNG？',a:'是。'}],links:[{href:'/compress',label:'压缩'},{href:'/resize',label:'调整大小'},{href:'/crop',label:'裁剪'},{href:'/watermark',label:'水印'},{href:'/jpg-to-png',label:'JPG→PNG'}]},
      'jpg-to-svg':{h2a:'JPG 转 SVG',steps:['<strong>图片</strong>。','<strong>宽度</strong>。','<strong>SVG</strong>。'],h2b:"免费 JPG→SVG",body:"<p>嵌入 SVG。</p>",h3why:'为什么？',why:"无损缩放。",faqs:[{q:'矢量化？',a:'不——包装器。'},{q:'保存？',a:'不会。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/image-to-ico',label:'转 ICO'},{href:'/compress',label:'压缩'},{href:'/resize',label:'调整大小'}]},
      'html-to-image':{h2a:'网站转图片',steps:['<strong>URL</strong>。','<strong>设置</strong>。','<strong>截取</strong>。','<strong>下载</strong>。'],h2b:'免费网页截图',body:'<p>捕获网页。</p>',h3why:'为什么？',why:'文档和存档。',faqs:[{q:'URL？',a:'公开页面。'},{q:'尺寸？',a:'手机、平板、桌面、Full HD。'},{q:'格式？',a:'JPG、PNG。'},{q:'免费？',a:'是。'},{q:'手机？',a:'是——375px。'}],links:[{href:'/compress',label:'压缩'},{href:'/resize',label:'调整大小'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/crop',label:'裁剪'},{href:'/watermark',label:'水印'}]},
    },
    about:{title:'关于 — RelahConvert',hero_h1_1:'关于',hero_h1_em:'RelahConvert',hero_p:'免费图片工具。',s1_h:'关于我们',s1_p1:'浏览器端免费工具。',s1_p2:'文件属于您。',s2_h:'使命',s2_p:'人人可用的专业工具。',s3_h:'为什么选择 RelahConvert？',s3_f1:'100% 免费',s3_f2:'设备端处理',s3_f3:'无广告',s3_f4:'所有现代浏览器'},
    contact:{title:'联系 — RelahConvert',hero_h1_1:'联系',hero_h1_em:'我们',hero_p:'问题或错误？',s1_h:'联系方式',s1_p:'1–2 天内回复。',s2_h:'请包含',s2_p1:'请告诉我们：',s2_p2:'• 工具<br>• 描述<br>• 浏览器'},
    privacy:{title:'隐私 — RelahConvert',hero_h1_1:'隐私',hero_h1_em:'政策',updated:'2026 年 3 月',s1_h:'无上传',s1_p:'浏览器本地处理。例外：HTML 转图片会将 URL 发送至第三方服务。',s2_h:'数据',s2_p1:'匿名数据。',s2_p2:'无个人信息。',s3_h:'Cookie',s3_p:'仅必要。参见 <a href="/cookies">政策</a>。',s4_h:'第三方',s4_p:'我们不出售数据。'},
    terms:{title:'条款 — RelahConvert',hero_h1_1:'使用',hero_h1_em:'条款',updated:'2026 年 3 月',s1_h:'使用',s1_p:'免费。',s2_h:'保证',s2_p:'无。',s3_h:'责任',s3_p:'有限。',s4_h:'所有权',s4_p:'我们所有。',s5_h:'变更',s5_p:'可能更新。'},
    cookies:{title:'Cookie — RelahConvert',hero_h1_1:'Cookie',hero_h1_em:'政策',updated:'2026 年 3 月',s1_h:'什么是 Cookie',s1_p:'文本文件。',s2_h:'使用',s2_p:'仅必要。',s3_h:'第三方',s3_p:'无。',s4_h:'管理',s4_p:'在浏览器中禁用。'},
  },`,

'zh-TW': `  'zh-TW':{
    nav_more_tools:'更多工具',
    nav_short:{'jpg-to-png':'JPG轉PNG','png-to-jpg':'PNG轉JPG','jpg-to-webp':'JPG轉WebP','webp-to-jpg':'WebP轉JPG','png-to-webp':'PNG轉WebP','webp-to-png':'WebP轉PNG','compress':'壓縮','resize':'調整大小','jpg-to-pdf':'JPG轉PDF','png-to-pdf':'PNG轉PDF','gif-to-jpg':'GIF轉JPG','gif-to-png':'GIF轉PNG','bmp-to-jpg':'BMP轉JPG','bmp-to-png':'BMP轉PNG','tiff-to-jpg':'TIFF轉JPG','jpg-to-gif':'JPG轉GIF','png-to-gif':'PNG轉GIF','crop':'裁剪','rotate':'旋轉','flip':'翻轉','grayscale':'灰階','watermark':'浮水印','round-corners':'圓角','remove-background':'移除背景','heic-to-jpg':'HEIC轉JPG','image-to-ico':'圖片轉ICO','jpg-to-svg':'JPG轉SVG','meme-generator':'迷因產生器','blur-face':'模糊臉部','html-to-image':'HTML轉圖片'},
    footer_copy:'© 2026 RelahConvert. 保留所有權利。',footer_company:'公司',footer_legal:'法律',footer_about:'關於',footer_contact:'聯絡',footer_privacy:'隱私政策',footer_terms:'使用條款',footer_cookies:'Cookie 政策',
    hero_badge:'✦ 免費 · 無需上傳 · 瀏覽器處理',hero_title_1:'您需要的所有工具',hero_title_2:'集於一處，',hero_title_em:'免費',
    hero_desc:'轉換、壓縮、調整大小和匯出圖片。檔案不會離開您的裝置。',
    card_compress_desc:'縮小 JPG、PNG 和 WebP 檔案。',card_resize_desc:'調整 JPG 和 PNG 圖片大小。',card_jpg_png_desc:'免費將 JPG 轉換為 PNG。',card_png_jpg_desc:'免費將 PNG 轉換為 JPG。',card_jpg_webp_desc:'免費將 JPG 轉換為 WebP。',card_webp_jpg_desc:'免費將 WebP 轉換為 JPG。',card_png_webp_desc:'免費將 PNG 轉換為 WebP。',card_webp_png_desc:'免費將 WebP 轉換為 PNG。',card_jpg_pdf_desc:'免費將 JPG 轉換為 PDF。',card_png_pdf_desc:'免費將 PNG 轉換為 PDF。',card_meme_generator_desc:'線上免費製作迷因。',card_blur_face_desc:'免費模糊臉部。自動或手動。',card_jpg_to_pdf_desc:'免費將 JPG 轉換為 PDF。',card_png_to_pdf_desc:'免費將 PNG 轉換為 PDF。',
    tool_title:{'jpg-to-png':'JPG→PNG 轉換器','png-to-jpg':'PNG→JPG 轉換器','jpg-to-webp':'JPG→WebP 轉換器','webp-to-jpg':'WebP→JPG 轉換器','png-to-webp':'PNG→WebP 轉換器','webp-to-png':'WebP→PNG 轉換器','gif-to-jpg':'GIF→JPG 轉換器','gif-to-png':'GIF→PNG 轉換器','bmp-to-jpg':'BMP→JPG 轉換器','bmp-to-png':'BMP→PNG 轉換器','tiff-to-jpg':'TIFF→JPG 轉換器','jpg-to-gif':'JPG→GIF 轉換器','png-to-gif':'PNG→GIF 轉換器'},
    tool_desc:{'jpg-to-png':'免費將 JPG 轉換為 PNG。','png-to-jpg':'免費將 PNG 轉換為 JPG。','jpg-to-webp':'將 JPG 轉換為 WebP。','webp-to-jpg':'免費將 WebP 轉換為 JPG。','png-to-webp':'將 PNG 轉換為 WebP。','webp-to-png':'將 WebP 轉換為 PNG。','gif-to-jpg':'免費將 GIF 轉換為 JPG。','gif-to-png':'免費將 GIF 轉換為 PNG。','bmp-to-jpg':'免費將 BMP 轉換為 JPG。','bmp-to-png':'免費將 BMP 轉換為 PNG。','tiff-to-jpg':'免費將 TIFF 轉換為 JPG。','jpg-to-gif':'免費將 JPG 轉換為 GIF。','png-to-gif':'免費將 PNG 轉換為 GIF。'},
    select_images:'選擇圖片',drop_hint:'或拖放圖片',add_more:'新增更多',download:'下載',download_zip:'下載 ZIP',processing:'處理中...',
    warn_wrong_format:'檔案已跳過。',warn_unsupported:'不支援的格式。',warn_too_large:'檔案太大。',warn_only_jpg_png:'只能調整 JPG 和 PNG 大小。',warn_wrong_fmt_tool:'格式錯誤！此工具僅接受',warn_files:'個檔案。',warn_png_to_jpg:'PNG 檔案將儲存為 JPG。',warn_wrong_fmt_short:'格式錯誤。',
    compress_title:'圖片',compress_title_em:'壓縮',compress_desc:'免費壓縮 JPG、PNG 和 WebP。',compress_btn:'壓縮圖片',compress_btn_loading:'壓縮中...',compress_result:'更小了！',compress_result_plural:'張圖片已',compress_result_singular:'張圖片已',
    resize_title:'圖片',resize_title_em:'調整大小',resize_desc:'免費調整 JPG 和 PNG 大小。',resize_btn:'調整大小',resize_btn_loading:'調整中...',resize_options:'選項',resize_by_pixels:'按像素',resize_by_percent:'按百分比',resize_width:'寬度 (px)',resize_height:'高度 (px)',resize_aspect:'保持比例',resize_custom_pct:'自訂 %',resize_of_original:'原始大小的',resize_warn_dims:'請輸入寬度或高度。',resize_warn_pct:'請輸入百分比。',resize_warn_invalid:'無效的尺寸。',
    convert_btn:'轉換圖片',convert_btn_loading:'轉換中...',convert_output_format:'輸出格式',convert_to_jpg:'轉換為 JPG',convert_to_png:'轉換為 PNG',convert_to_webp:'轉換為 WebP',also_convert:'也可轉換：',
    pdf_btn:'轉換為 PDF',pdf_btn_loading:'轉換中...',pdf_options:'PDF 選項',pdf_mode_one:'每張圖片一個 PDF',pdf_mode_all:'全部合併為一個 PDF',
    whats_next:'接下來？',next_compress:'壓縮',next_resize:'調整大小',next_to_png:'轉換為 PNG',next_to_jpg:'轉換為 JPG',convert_to_ico:'轉換為 ICO',up_to_25_files:'最多 25 個檔案',ico_sizes_label:'ICO 尺寸（選擇需要的）',svg_notice:'此工具將圖片嵌入 SVG 容器——使其可無限縮放。如需完整向量化，請使用 Inkscape。',next_to_webp:'轉換為 WebP',next_to_pdf:'轉換為 PDF',
    hti_desc:'將任何網站擷取為圖片。輸入 URL 並下載截圖。',hti_url_label:'網站 URL',hti_screen_size:'螢幕大小',hti_format:'格式',hti_btn:'擷取螢幕',hti_loading:'擷取中…',hti_download:'下載截圖',hti_error:'擷取失敗。請檢查 URL 後重試。',hti_url_error:'請輸入 URL。',hti_mobile:'手機',hti_tablet:'平板',hti_desktop:'桌面',hti_fullhd:'Full HD',
    filter:{all:'全部',optimize:'最佳化',edit:'編輯',convert:'轉換',create:'建立',privacy:'隱私'},
    round_corners_title_1:'圖片',round_corners_title_em:'圓角',round_corners_btn:'圓角處理',round_corners_panel:'圓角半徑',round_corners_preset_slight:'輕微',round_corners_preset_rounded:'圓角',round_corners_preset_very:'大圓角',round_corners_preset_circle:'圓形',
    meme_generator_title:'迷因產生器',meme_generator_desc:'線上製作迷因。選擇範本或上傳圖片。隱私安全——在瀏覽器中處理。',meme_generator_upload_btn:'上傳圖片',meme_generator_template_btn:'選擇範本',meme_generator_add_text_btn:'新增文字',meme_generator_add_image_btn:'新增圖片',meme_generator_download_btn:'下載迷因',meme_generator_text_inside:'文字在內',meme_generator_text_outside:'文字在外',meme_generator_band_color:'色帶顏色',meme_generator_top_text:'頂部文字',meme_generator_bottom_text:'底部文字（選填）',
    meme_title:'迷因',meme_title_em:'產生器',meme_sub:'線上製作迷因。選擇範本或上傳圖片。隱私安全——在瀏覽器中處理。',meme_upload_btn:'上傳圖片',meme_template_btn:'選擇範本',meme_editor:'迷因編輯器',meme_text_inside:'文字在內',meme_text_outside:'文字在外',meme_band_color:'色帶顏色：',meme_top_text:'頂部文字（選填）',meme_bottom_text:'底部文字（選填）',meme_add_text:'新增文字',meme_add_image:'新增圖片',meme_download:'下載迷因',meme_choose_templ:'選擇迷因範本',
    blur_face_title:'模糊',blur_face_title_em:'臉部',blur_face_sub:'模糊照片中的臉部。自動或手動偵測。最多 25 張圖片。隱私安全——在瀏覽器中處理。',blur_face_upload:'上傳圖片',blur_face_download:'下載圖片',blur_face_amount:'模糊程度',blur_face_detecting:'偵測臉部中…',blur_face_none:'未偵測到臉部。請嘗試更清晰的照片或使用手動模糊。',blur_face_found:'個臉部已偵測',blur_face_manual:'新增模糊',blur_face_auto:'自動偵測',blur_face_mode:'模式',blur_face_select_mode:'選擇模式以開始。',blur_face_draw:'在圖片上點擊並拖曳以模糊區域。',blur_face_editor:'模糊編輯器',blur_face_regions:'模糊區域',blur_face_download_zip:'下載全部為 ZIP',blur_face_reset:'上傳新圖片',blur_face_images_label:'圖片',blur_face_drop:'拖放圖片到此處或點擊上傳',blur_face_drop_sub:'JPG、PNG、WebP · 最多 25 張 · 最大 200 MB',blur_face_processing:'處理中',blur_face_creating_zip:'建立 ZIP 中…',blur_face_batch_failed:'批次下載失敗',
    seo_faq_title:'常見問題',seo_also_try:'也試試',
    seo:{
      'jpg-to-png':{h2a:'免費將 JPG 轉 PNG',steps:['<strong>選擇 JPG</strong>。','<strong>轉換</strong>。','<strong>下載 PNG</strong>。'],h2b:"免費 JPG→PNG",body:"<p>瀏覽器中轉換。</p>",h3why:'為什麼？',why:"PNG 支援透明。",faqs:[{q:'儲存檔案？',a:'不會。'}],links:[{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/compress',label:'壓縮'},{href:'/gif-to-png',label:'GIF→PNG'},{href:'/resize',label:'調整大小'}]},
      'png-to-jpg':{h2a:'免費將 PNG 轉 JPG',steps:['<strong>選擇 PNG</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 PNG→JPG",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"小 60–80%。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'壓縮'},{href:'/bmp-to-jpg',label:'BMP→JPG'},{href:'/resize',label:'調整大小'}]},
      'jpg-to-webp':{h2a:'JPG 轉 WebP',steps:['<strong>JPG</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 JPG→WebP",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"小 25–35%。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/webp-to-jpg',label:'WebP→JPG'},{href:'/compress',label:'壓縮'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'調整大小'}]},
      'webp-to-jpg':{h2a:'WebP 轉 JPG',steps:['<strong>WebP</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 WebP→JPG",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"到處可開啟。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/jpg-to-webp',label:'JPG→WebP'},{href:'/compress',label:'壓縮'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'調整大小'}]},
      'png-to-webp':{h2a:'PNG 轉 WebP',steps:['<strong>PNG</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 PNG→WebP",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"小 30–50%。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/webp-to-png',label:'WebP→PNG'},{href:'/compress',label:'壓縮'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'調整大小'}]},
      'webp-to-png':{h2a:'WebP 轉 PNG',steps:['<strong>WebP</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 WebP→PNG",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"相容所有編輯器。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/png-to-webp',label:'PNG→WebP'},{href:'/compress',label:'壓縮'},{href:'/webp-to-jpg',label:'WebP→JPG'},{href:'/resize',label:'調整大小'}]},
      'gif-to-jpg':{h2a:'GIF 轉 JPG',steps:['<strong>GIF</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 GIF→JPG",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"小 60–80%。",faqs:[{q:'動畫？',a:'僅第一幀。'},{q:'儲存？',a:'不會。'}],links:[{href:'/gif-to-png',label:'GIF→PNG'},{href:'/compress',label:'壓縮'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'調整大小'}]},
      'gif-to-png':{h2a:'GIF 轉 PNG',steps:['<strong>GIF</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 GIF→PNG",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"百萬色彩。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/gif-to-jpg',label:'GIF→JPG'},{href:'/compress',label:'壓縮'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'調整大小'}]},
      'bmp-to-jpg':{h2a:'BMP 轉 JPG',steps:['<strong>BMP</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 BMP→JPG",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"BMP 大 10–20 倍。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/bmp-to-png',label:'BMP→PNG'},{href:'/compress',label:'壓縮'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'調整大小'}]},
      'bmp-to-png':{h2a:'BMP 轉 PNG',steps:['<strong>BMP</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 BMP→PNG",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"小 60–80%。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/bmp-to-jpg',label:'BMP→JPG'},{href:'/compress',label:'壓縮'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'調整大小'}]},
      'tiff-to-jpg':{h2a:'TIFF 轉 JPG',steps:['<strong>TIFF</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 TIFF→JPG",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"小 90–95%。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'壓縮'},{href:'/bmp-to-jpg',label:'BMP→JPG'},{href:'/resize',label:'調整大小'}]},
      'jpg-to-gif':{h2a:'JPG 轉 GIF',steps:['<strong>JPG</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 JPG→GIF",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"全平台相容。",faqs:[{q:'動畫？',a:'不是。'},{q:'儲存？',a:'不會。'}],links:[{href:'/png-to-gif',label:'PNG→GIF'},{href:'/gif-to-jpg',label:'GIF→JPG'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'壓縮'}]},
      'png-to-gif':{h2a:'PNG 轉 GIF',steps:['<strong>PNG</strong>。','<strong>轉換</strong>。','<strong>下載</strong>。'],h2b:"免費 PNG→GIF",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"通用相容。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/jpg-to-gif',label:'JPG→GIF'},{href:'/gif-to-png',label:'GIF→PNG'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/compress',label:'壓縮'}]},
      'crop':{h2a:'無需上傳裁剪',steps:['<strong>圖片</strong>。','<strong>裁剪</strong>。','<strong>下載</strong>。'],h2b:"免費裁剪",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"去除不需要的部分。",faqs:[{q:'精確尺寸？',a:'是。'},{q:'品質？',a:'無損。'},{q:'儲存？',a:'不會。'}],links:[{href:'/resize',label:'調整大小'},{href:'/rotate',label:'旋轉'},{href:'/compress',label:'壓縮'},{href:'/flip',label:'翻轉'}]},
      'rotate':{h2a:'無需上傳旋轉',steps:['<strong>圖片</strong>。','<strong>旋轉</strong>。','<strong>下載</strong>。'],h2b:"免費旋轉",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"修正方向。",faqs:[{q:'角度？',a:'自由。'},{q:'品質？',a:'無損。'},{q:'儲存？',a:'不會。'}],links:[{href:'/crop',label:'裁剪'},{href:'/flip',label:'翻轉'},{href:'/resize',label:'調整大小'},{href:'/compress',label:'壓縮'}]},
      'flip':{h2a:'無需上傳翻轉',steps:['<strong>圖片</strong>。','<strong>方向</strong>。','<strong>下載</strong>。'],h2b:"免費翻轉",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"鏡像效果。",faqs:[{q:'區別？',a:'鏡像 vs 角度。'},{q:'透明？',a:'保留。'},{q:'儲存？',a:'不會。'}],links:[{href:'/rotate',label:'旋轉'},{href:'/crop',label:'裁剪'},{href:'/resize',label:'調整大小'},{href:'/compress',label:'壓縮'}]},
      'grayscale':{h2a:'轉為黑白',steps:['<strong>圖片</strong>——最多 25 張。','<strong>預覽</strong>。','<strong>下載</strong>。'],h2b:"免費黑白",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"經典美感。",faqs:[{q:'多張？',a:'是——25。'},{q:'品質？',a:'無損。'},{q:'儲存？',a:'不會。'}],links:[{href:'/compress',label:'壓縮'},{href:'/watermark',label:'浮水印'},{href:'/rotate',label:'旋轉'},{href:'/resize',label:'調整大小'}]},
      'watermark':{h2a:'新增浮水印',steps:['<strong>圖片</strong>——最多 25 張。','<strong>圖層</strong>。','<strong>下載</strong>。'],h2b:"免費浮水印",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"保護照片。",faqs:[{q:'Logo？',a:'是。'},{q:'多個？',a:'是。'},{q:'儲存？',a:'不會。'}],links:[{href:'/compress',label:'壓縮'},{href:'/resize',label:'調整大小'},{href:'/crop',label:'裁剪'},{href:'/rotate',label:'旋轉'}]},
      'remove-background':{h2a:'移除背景',steps:['<strong>圖片</strong>。','<strong>AI 移除</strong>。','<strong>PNG</strong>。'],h2b:"免費移除背景",body:"<p>瀏覽器 AI。</p>",h3why:'為什麼？',why:"放置在任何背景上。",faqs:[{q:'儲存？',a:'不會。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'壓縮'},{href:'/resize',label:'調整大小'},{href:'/crop',label:'裁剪'}]},
      'heic-to-jpg':{h2a:'HEIC 轉 JPG',steps:['<strong>HEIC</strong>。','<strong>轉換</strong>。','<strong>JPG</strong>。'],h2b:"免費 HEIC→JPG",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"JPG 相容性高。HEIC 在 Windows 上無法開啟。",faqs:[{q:'多張？',a:'是。'},{q:'儲存？',a:'不會。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'壓縮'},{href:'/resize',label:'調整大小'},{href:'/jpg-to-webp',label:'JPG→WebP'}]},
      'image-to-ico':{h2a:'轉為 ICO',steps:['<strong>圖片</strong>。','<strong>尺寸</strong>。','<strong>ICO</strong>。'],h2b:"免費 ICO 轉換",body:"<p>瀏覽器中。</p>",h3why:'為什麼？',why:"網站圖示和 Windows 圖示。",faqs:[{q:'多尺寸？',a:'是。'},{q:'儲存？',a:'不會。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'調整大小'},{href:'/compress',label:'壓縮'},{href:'/crop',label:'裁剪'}]},
      'round-corners':{h2a:'免費圓角處理',steps:['<strong>圖片</strong>。','<strong>半徑</strong>。','<strong>圓角</strong>。','<strong>PNG</strong>。'],h2b:'免費圓角',body:'<p>瀏覽器中。</p>',h3why:'為什麼？',why:'現代外觀。',faqs:[{q:'格式？',a:'PNG。'},{q:'多張？',a:'是——25。'},{q:'上傳？',a:'不會。'},{q:'圓形？',a:'是——50%。'},{q:'調節？',a:'0–50%。'}],links:[{href:'/crop',label:'裁剪'},{href:'/resize',label:'調整大小'},{href:'/rotate',label:'旋轉'},{href:'/compress',label:'壓縮'},{href:'/remove-background',label:'移除背景'},{href:'/jpg-to-png',label:'JPG→PNG'}]},
      'meme-generator':{h2a:'免費製作迷因',steps:['上傳或範本。','文字。','樣式。','下載。'],h2b:"免費迷因產生器",body:'瀏覽器中製作迷因。',h3why:'為什麼？',why:'最快的分享方式。',faqs:[{q:'上傳？',a:'不會。'},{q:'自己的圖？',a:'是。'},{q:'浮水印？',a:'沒有。'},{q:'多文字？',a:'是。'},{q:'字型？',a:'Impact, Arial Black, Arial, Verdana, Times New Roman, Georgia, Courier New, Comic Sans。'},{q:'PNG？',a:'是。'}],links:[{href:'/compress',label:'壓縮'},{href:'/resize',label:'調整大小'},{href:'/crop',label:'裁剪'},{href:'/watermark',label:'浮水印'},{href:'/jpg-to-png',label:'JPG→PNG'}]},
      'jpg-to-svg':{h2a:'JPG 轉 SVG',steps:['<strong>圖片</strong>。','<strong>寬度</strong>。','<strong>SVG</strong>。'],h2b:"免費 JPG→SVG",body:"<p>嵌入 SVG。</p>",h3why:'為什麼？',why:"無損縮放。",faqs:[{q:'向量化？',a:'不——包裝器。'},{q:'儲存？',a:'不會。'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/image-to-ico',label:'轉 ICO'},{href:'/compress',label:'壓縮'},{href:'/resize',label:'調整大小'}]},
      'html-to-image':{h2a:'網站轉圖片',steps:['<strong>URL</strong>。','<strong>設定</strong>。','<strong>擷取</strong>。','<strong>下載</strong>。'],h2b:'免費網頁截圖',body:'<p>擷取網頁。</p>',h3why:'為什麼？',why:'文件和存檔。',faqs:[{q:'URL？',a:'公開頁面。'},{q:'尺寸？',a:'手機、平板、桌面、Full HD。'},{q:'格式？',a:'JPG、PNG。'},{q:'免費？',a:'是。'},{q:'手機？',a:'是——375px。'}],links:[{href:'/compress',label:'壓縮'},{href:'/resize',label:'調整大小'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/crop',label:'裁剪'},{href:'/watermark',label:'浮水印'}]},
    },
    about:{title:'關於 — RelahConvert',hero_h1_1:'關於',hero_h1_em:'RelahConvert',hero_p:'免費圖片工具。',s1_h:'關於我們',s1_p1:'瀏覽器端免費工具。',s1_p2:'檔案屬於您。',s2_h:'使命',s2_p:'人人可用的專業工具。',s3_h:'為什麼選擇 RelahConvert？',s3_f1:'100% 免費',s3_f2:'裝置端處理',s3_f3:'無廣告',s3_f4:'所有現代瀏覽器'},
    contact:{title:'聯絡 — RelahConvert',hero_h1_1:'聯絡',hero_h1_em:'我們',hero_p:'問題或錯誤？',s1_h:'聯絡方式',s1_p:'1–2 天內回覆。',s2_h:'請包含',s2_p1:'請告訴我們：',s2_p2:'• 工具<br>• 描述<br>• 瀏覽器'},
    privacy:{title:'隱私 — RelahConvert',hero_h1_1:'隱私',hero_h1_em:'政策',updated:'2026 年 3 月',s1_h:'無上傳',s1_p:'瀏覽器本地處理。例外：HTML 轉圖片會將 URL 傳送至第三方服務。',s2_h:'資料',s2_p1:'匿名資料。',s2_p2:'無個人資訊。',s3_h:'Cookie',s3_p:'僅必要。參見 <a href="/cookies">政策</a>。',s4_h:'第三方',s4_p:'我們不出售資料。'},
    terms:{title:'條款 — RelahConvert',hero_h1_1:'使用',hero_h1_em:'條款',updated:'2026 年 3 月',s1_h:'使用',s1_p:'免費。',s2_h:'保證',s2_p:'無。',s3_h:'責任',s3_p:'有限。',s4_h:'所有權',s4_p:'我們所有。',s5_h:'變更',s5_p:'可能更新。'},
    cookies:{title:'Cookie — RelahConvert',hero_h1_1:'Cookie',hero_h1_em:'政策',updated:'2026 年 3 月',s1_h:'什麼是 Cookie',s1_p:'文字檔案。',s2_h:'使用',s2_p:'僅必要。',s3_h:'第三方',s3_p:'無。',s4_h:'管理',s4_p:'在瀏覽器中停用。'},
  },`,

bg: `  bg:{
    nav_more_tools:'Още инструменти',
    nav_short:{'jpg-to-png':'JPG в PNG','png-to-jpg':'PNG в JPG','jpg-to-webp':'JPG в WebP','webp-to-jpg':'WebP в JPG','png-to-webp':'PNG в WebP','webp-to-png':'WebP в PNG','compress':'Компресиране','resize':'Преоразмеряване','jpg-to-pdf':'JPG в PDF','png-to-pdf':'PNG в PDF','gif-to-jpg':'GIF в JPG','gif-to-png':'GIF в PNG','bmp-to-jpg':'BMP в JPG','bmp-to-png':'BMP в PNG','tiff-to-jpg':'TIFF в JPG','jpg-to-gif':'JPG в GIF','png-to-gif':'PNG в GIF','crop':'Изрязване','rotate':'Завъртане','flip':'Обръщане','grayscale':'Сиво','watermark':'Воден знак','round-corners':'Заоблени ъгли','remove-background':'Премахване на фон','heic-to-jpg':'HEIC в JPG','image-to-ico':'Изображение в ICO','jpg-to-svg':'JPG в SVG','meme-generator':'Генератор на мемета','blur-face':'Замъгляване на лице','html-to-image':'HTML в изображение'},
    footer_copy:'© 2026 RelahConvert. Всички права запазени.',footer_company:'Компания',footer_legal:'Правна информация',footer_about:'За нас',footer_contact:'Контакт',footer_privacy:'Поверителност',footer_terms:'Условия',footer_cookies:'Бисквитки',
    hero_badge:'✦ Безплатно · Без качване · Само браузър',hero_title_1:'Всички инструменти',hero_title_2:'от които се нуждаете,',hero_title_em:'безплатно',
    hero_desc:'Конвертирайте, компресирайте, преоразмерявайте и експортирайте изображения. Файловете не напускат устройството ви.',
    card_compress_desc:'Намалете размера на JPG, PNG и WebP.',card_resize_desc:'Преоразмерете JPG и PNG.',card_jpg_png_desc:'Конвертирайте JPG в PNG безплатно.',card_png_jpg_desc:'Конвертирайте PNG в JPG безплатно.',card_jpg_webp_desc:'Конвертирайте JPG в WebP безплатно.',card_webp_jpg_desc:'Конвертирайте WebP в JPG безплатно.',card_png_webp_desc:'Конвертирайте PNG в WebP безплатно.',card_webp_png_desc:'Конвертирайте WebP в PNG безплатно.',card_jpg_pdf_desc:'Конвертирайте JPG в PDF безплатно.',card_png_pdf_desc:'Конвертирайте PNG в PDF безплатно.',card_meme_generator_desc:'Създайте мемета онлайн безплатно.',card_blur_face_desc:'Замъглете лица безплатно.',card_jpg_to_pdf_desc:'Конвертирайте JPG в PDF безплатно.',card_png_to_pdf_desc:'Конвертирайте PNG в PDF безплатно.',
    tool_title:{'jpg-to-png':'JPG→PNG конвертор','png-to-jpg':'PNG→JPG конвертор','jpg-to-webp':'JPG→WebP конвертор','webp-to-jpg':'WebP→JPG конвертор','png-to-webp':'PNG→WebP конвертор','webp-to-png':'WebP→PNG конвертор','gif-to-jpg':'GIF→JPG конвертор','gif-to-png':'GIF→PNG конвертор','bmp-to-jpg':'BMP→JPG конвертор','bmp-to-png':'BMP→PNG конвертор','tiff-to-jpg':'TIFF→JPG конвертор','jpg-to-gif':'JPG→GIF конвертор','png-to-gif':'PNG→GIF конвертор'},
    tool_desc:{'jpg-to-png':'Конвертирайте JPG в PNG безплатно.','png-to-jpg':'Конвертирайте PNG в JPG безплатно.','jpg-to-webp':'Конвертирайте JPG в WebP.','webp-to-jpg':'Конвертирайте WebP в JPG безплатно.','png-to-webp':'Конвертирайте PNG в WebP.','webp-to-png':'Конвертирайте WebP в PNG.','gif-to-jpg':'Конвертирайте GIF в JPG безплатно.','gif-to-png':'Конвертирайте GIF в PNG безплатно.','bmp-to-jpg':'Конвертирайте BMP в JPG безплатно.','bmp-to-png':'Конвертирайте BMP в PNG безплатно.','tiff-to-jpg':'Конвертирайте TIFF в JPG безплатно.','jpg-to-gif':'Конвертирайте JPG в GIF безплатно.','png-to-gif':'Конвертирайте PNG в GIF безплатно.'},
    select_images:'Изберете изображения',drop_hint:'или пуснете изображения тук',add_more:'Добавете още',download:'Изтегляне',download_zip:'Изтегляне ZIP',processing:'Обработка...',
    warn_wrong_format:'Файлът е пропуснат.',warn_unsupported:'Неподдържан формат.',warn_too_large:'Файлът е твърде голям.',warn_only_jpg_png:'Само JPG и PNG могат да се преоразмеряват.',warn_wrong_fmt_tool:'Грешен формат! Този инструмент приема само',warn_files:'файла.',warn_png_to_jpg:'PNG файловете ще бъдат запазени като JPG.',warn_wrong_fmt_short:'Грешен формат.',
    compress_title:'Компресиране',compress_title_em:'на изображения',compress_desc:'Компресирайте JPG, PNG и WebP безплатно.',compress_btn:'Компресиране',compress_btn_loading:'Компресиране...',compress_result:'по-малко!',compress_result_plural:'изображения са',compress_result_singular:'изображение е',
    resize_title:'Преоразмеряване',resize_title_em:'на изображения',resize_desc:'Преоразмерете JPG и PNG безплатно.',resize_btn:'Преоразмеряване',resize_btn_loading:'Преоразмеряване...',resize_options:'Опции',resize_by_pixels:'В пиксели',resize_by_percent:'В проценти',resize_width:'Ширина (px)',resize_height:'Височина (px)',resize_aspect:'Запазване на пропорциите',resize_custom_pct:'Потребителски %',resize_of_original:'от оригиналния размер',resize_warn_dims:'Въведете ширина или височина.',resize_warn_pct:'Въведете процент.',resize_warn_invalid:'Невалидни размери.',
    convert_btn:'Конвертиране',convert_btn_loading:'Конвертиране...',convert_output_format:'Изходен формат',convert_to_jpg:'В JPG',convert_to_png:'В PNG',convert_to_webp:'В WebP',also_convert:'Също конвертирайте:',
    pdf_btn:'В PDF',pdf_btn_loading:'Конвертиране...',pdf_options:'PDF опции',pdf_mode_one:'Един PDF на изображение',pdf_mode_all:'Всички в един PDF',
    whats_next:'Какво следва?',next_compress:'Компресиране',next_resize:'Преоразмеряване',next_to_png:'В PNG',next_to_jpg:'В JPG',convert_to_ico:'В ICO',up_to_25_files:'до 25 файла',ico_sizes_label:'ICO размери',svg_notice:'Този инструмент вгражда изображението в SVG контейнер. За пълна векторизация използвайте Inkscape.',next_to_webp:'В WebP',next_to_pdf:'В PDF',
    hti_desc:'Заснемете всеки уебсайт като изображение.',hti_url_label:'URL на сайта',hti_screen_size:'Размер на екрана',hti_format:'Формат',hti_btn:'Заснемане',hti_loading:'Заснемане…',hti_download:'Изтегляне',hti_error:'Неуспешно. Проверете URL.',hti_url_error:'Въведете URL.',hti_mobile:'Мобилен',hti_tablet:'Таблет',hti_desktop:'Десктоп',hti_fullhd:'Full HD',
    filter:{all:'Всички',optimize:'Оптимизиране',edit:'Редактиране',convert:'Конвертиране',create:'Създаване',privacy:'Поверителност'},
    round_corners_title_1:'Заоблени',round_corners_title_em:'ъгли',round_corners_btn:'Заобляне',round_corners_panel:'Радиус',round_corners_preset_slight:'Леко',round_corners_preset_rounded:'Заоблено',round_corners_preset_very:'Много заоблено',round_corners_preset_circle:'Кръг',
    meme_generator_title:'Генератор на мемета',meme_generator_desc:'Създайте мемета онлайн. Изберете шаблон или качете изображение. Поверително — в браузъра.',meme_generator_upload_btn:'Качване',meme_generator_template_btn:'Шаблон',meme_generator_add_text_btn:'Добавяне на текст',meme_generator_add_image_btn:'Добавяне на изображение',meme_generator_download_btn:'Изтегляне на мем',meme_generator_text_inside:'Текст вътре',meme_generator_text_outside:'Текст отвън',meme_generator_band_color:'Цвят на лентата',meme_generator_top_text:'Горен текст',meme_generator_bottom_text:'Долен текст (по избор)',
    meme_title:'Генератор',meme_title_em:'на мемета',meme_sub:'Създайте мемета онлайн. Изберете шаблон или качете изображение. Поверително — в браузъра.',meme_upload_btn:'Качване',meme_template_btn:'Шаблон',meme_editor:'Редактор на мемета',meme_text_inside:'Текст вътре',meme_text_outside:'Текст отвън',meme_band_color:'Цвят на лентата:',meme_top_text:'Горен текст (по избор)',meme_bottom_text:'Долен текст (по избор)',meme_add_text:'ДОБАВЯНЕ НА ТЕКСТ',meme_add_image:'ДОБАВЯНЕ НА ИЗОБРАЖЕНИЕ',meme_download:'Изтегляне на мем',meme_choose_templ:'Изберете шаблон',
    blur_face_title:'Замъгляване',blur_face_title_em:'на лице',blur_face_sub:'Замъглете лица в снимки. Автоматично или ръчно. До 25 изображения. Поверително — в браузъра.',blur_face_upload:'Качване',blur_face_download:'Изтегляне',blur_face_amount:'Степен на замъгляване',blur_face_detecting:'Откриване на лица…',blur_face_none:'Не са открити лица.',blur_face_found:'лица открити',blur_face_manual:'Ръчно замъгляване',blur_face_auto:'Автоматично',blur_face_mode:'Режим',blur_face_select_mode:'Изберете режим.',blur_face_draw:'Щракнете и плъзнете за замъгляване.',blur_face_editor:'Редактор',blur_face_regions:'Области',blur_face_download_zip:'ZIP',blur_face_reset:'Ново изображение',blur_face_images_label:'Изображения',blur_face_drop:'Пуснете изображения тук',blur_face_drop_sub:'JPG, PNG, WebP · До 25 · Макс 200 MB',blur_face_processing:'Обработка',blur_face_creating_zip:'Създаване на ZIP…',blur_face_batch_failed:'Грешка при пакетно изтегляне',
    seo_faq_title:'Често задавани въпроси',seo_also_try:'Опитайте също',
    seo:{
      'jpg-to-png':{h2a:'JPG в PNG безплатно',steps:['<strong>JPG</strong>.','<strong>Конвертиране</strong>.','<strong>PNG</strong>.'],h2b:"Безплатен JPG→PNG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"PNG поддържа прозрачност.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/compress',label:'Компресиране'},{href:'/gif-to-png',label:'GIF→PNG'},{href:'/resize',label:'Преоразмеряване'}]},
      'png-to-jpg':{h2a:'PNG в JPG',steps:['<strong>PNG</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен PNG→JPG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"60–80% по-малко.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'Компресиране'},{href:'/bmp-to-jpg',label:'BMP→JPG'},{href:'/resize',label:'Преоразмеряване'}]},
      'jpg-to-webp':{h2a:'JPG в WebP',steps:['<strong>JPG</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен JPG→WebP",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"25–35% по-малко.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/webp-to-jpg',label:'WebP→JPG'},{href:'/compress',label:'Компресиране'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'Преоразмеряване'}]},
      'webp-to-jpg':{h2a:'WebP в JPG',steps:['<strong>WebP</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен WebP→JPG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Отваря се навсякъде.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/jpg-to-webp',label:'JPG→WebP'},{href:'/compress',label:'Компресиране'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'Преоразмеряване'}]},
      'png-to-webp':{h2a:'PNG в WebP',steps:['<strong>PNG</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен PNG→WebP",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"30–50% по-малко.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/webp-to-png',label:'WebP→PNG'},{href:'/compress',label:'Компресиране'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'Преоразмеряване'}]},
      'webp-to-png':{h2a:'WebP в PNG',steps:['<strong>WebP</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен WebP→PNG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Съвместим с всички редактори.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/png-to-webp',label:'PNG→WebP'},{href:'/compress',label:'Компресиране'},{href:'/webp-to-jpg',label:'WebP→JPG'},{href:'/resize',label:'Преоразмеряване'}]},
      'gif-to-jpg':{h2a:'GIF в JPG',steps:['<strong>GIF</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен GIF→JPG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"60–80% по-малко.",faqs:[{q:'Анимация?',a:'Само първият кадър.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/gif-to-png',label:'GIF→PNG'},{href:'/compress',label:'Компресиране'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'Преоразмеряване'}]},
      'gif-to-png':{h2a:'GIF в PNG',steps:['<strong>GIF</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен GIF→PNG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Милиони цветове.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/gif-to-jpg',label:'GIF→JPG'},{href:'/compress',label:'Компресиране'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'Преоразмеряване'}]},
      'bmp-to-jpg':{h2a:'BMP в JPG',steps:['<strong>BMP</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен BMP→JPG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"BMP е 10–20x по-голям.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/bmp-to-png',label:'BMP→PNG'},{href:'/compress',label:'Компресиране'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'Преоразмеряване'}]},
      'bmp-to-png':{h2a:'BMP в PNG',steps:['<strong>BMP</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен BMP→PNG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"60–80% по-малко.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/bmp-to-jpg',label:'BMP→JPG'},{href:'/compress',label:'Компресиране'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/resize',label:'Преоразмеряване'}]},
      'tiff-to-jpg':{h2a:'TIFF в JPG',steps:['<strong>TIFF</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен TIFF→JPG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"90–95% по-малко.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'Компресиране'},{href:'/bmp-to-jpg',label:'BMP→JPG'},{href:'/resize',label:'Преоразмеряване'}]},
      'jpg-to-gif':{h2a:'JPG в GIF',steps:['<strong>JPG</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен JPG→GIF",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Универсална съвместимост.",faqs:[{q:'Анимация?',a:'Не.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/png-to-gif',label:'PNG→GIF'},{href:'/gif-to-jpg',label:'GIF→JPG'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'Компресиране'}]},
      'png-to-gif':{h2a:'PNG в GIF',steps:['<strong>PNG</strong>.','<strong>Конвертиране</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен PNG→GIF",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Универсална съвместимост.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/jpg-to-gif',label:'JPG→GIF'},{href:'/gif-to-png',label:'GIF→PNG'},{href:'/png-to-jpg',label:'PNG→JPG'},{href:'/compress',label:'Компресиране'}]},
      'crop':{h2a:'Изрязване без качване',steps:['<strong>Изображение</strong>.','<strong>Изрязване</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатно изрязване",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Премахнете ненужното.",faqs:[{q:'Точни размери?',a:'Да.'},{q:'Качество?',a:'Без загуба.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/resize',label:'Преоразмеряване'},{href:'/rotate',label:'Завъртане'},{href:'/compress',label:'Компресиране'},{href:'/flip',label:'Обръщане'}]},
      'rotate':{h2a:'Завъртане без качване',steps:['<strong>Изображение</strong>.','<strong>Завъртане</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатно завъртане",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Коригирайте ориентацията.",faqs:[{q:'Ъгъл?',a:'Свободен.'},{q:'Качество?',a:'Без загуба.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/crop',label:'Изрязване'},{href:'/flip',label:'Обръщане'},{href:'/resize',label:'Преоразмеряване'},{href:'/compress',label:'Компресиране'}]},
      'flip':{h2a:'Обръщане без качване',steps:['<strong>Изображение</strong>.','<strong>Посока</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатно обръщане",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Огледален ефект.",faqs:[{q:'Разлика?',a:'Огледало vs ъгъл.'},{q:'Прозрачност?',a:'Запазва се.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/rotate',label:'Завъртане'},{href:'/crop',label:'Изрязване'},{href:'/resize',label:'Преоразмеряване'},{href:'/compress',label:'Компресиране'}]},
      'grayscale':{h2a:'Черно-бяло',steps:['<strong>Изображения</strong> — до 25.','<strong>Преглед</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатно черно-бяло",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Класическа естетика.",faqs:[{q:'Няколко?',a:'Да — 25.'},{q:'Качество?',a:'Без загуба.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/compress',label:'Компресиране'},{href:'/watermark',label:'Воден знак'},{href:'/rotate',label:'Завъртане'},{href:'/resize',label:'Преоразмеряване'}]},
      'watermark':{h2a:'Воден знак',steps:['<strong>Изображения</strong> — до 25.','<strong>Слоеве</strong>.','<strong>Изтегляне</strong>.'],h2b:"Безплатен воден знак",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Защитете снимките.",faqs:[{q:'Лого?',a:'Да.'},{q:'Няколко?',a:'Да.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/compress',label:'Компресиране'},{href:'/resize',label:'Преоразмеряване'},{href:'/crop',label:'Изрязване'},{href:'/rotate',label:'Завъртане'}]},
      'remove-background':{h2a:'Премахване на фон',steps:['<strong>Изображение</strong>.','<strong>AI премахване</strong>.','<strong>PNG</strong>.'],h2b:"Безплатно премахване на фон",body:"<p>AI в браузъра.</p>",h3why:'Защо?',why:"Поставете на всякакъв фон.",faqs:[{q:'Запазване?',a:'Не.'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'Компресиране'},{href:'/resize',label:'Преоразмеряване'},{href:'/crop',label:'Изрязване'}]},
      'heic-to-jpg':{h2a:'HEIC в JPG',steps:['<strong>HEIC</strong>.','<strong>Конвертиране</strong>.','<strong>JPG</strong>.'],h2b:"Безплатен HEIC→JPG",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"JPG е съвместим. HEIC не се отваря в Windows.",faqs:[{q:'Няколко?',a:'Да.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/compress',label:'Компресиране'},{href:'/resize',label:'Преоразмеряване'},{href:'/jpg-to-webp',label:'JPG→WebP'}]},
      'image-to-ico':{h2a:'В ICO',steps:['<strong>Изображение</strong>.','<strong>Размери</strong>.','<strong>ICO</strong>.'],h2b:"Безплатен ICO",body:"<p>В браузъра.</p>",h3why:'Защо?',why:"Фавикони и икони за Windows.",faqs:[{q:'Няколко размера?',a:'Да.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/resize',label:'Преоразмеряване'},{href:'/compress',label:'Компресиране'},{href:'/crop',label:'Изрязване'}]},
      'round-corners':{h2a:'Заоблени ъгли безплатно',steps:['<strong>Изображение</strong>.','<strong>Радиус</strong>.','<strong>Заобляне</strong>.','<strong>PNG</strong>.'],h2b:'Безплатни заоблени ъгли',body:'<p>В браузъра.</p>',h3why:'Защо?',why:'Модерен вид.',faqs:[{q:'Формат?',a:'PNG.'},{q:'Няколко?',a:'Да — 25.'},{q:'Качване?',a:'Не.'},{q:'Кръг?',a:'Да — 50%.'},{q:'Контрол?',a:'0–50%.'}],links:[{href:'/crop',label:'Изрязване'},{href:'/resize',label:'Преоразмеряване'},{href:'/rotate',label:'Завъртане'},{href:'/compress',label:'Компресиране'},{href:'/remove-background',label:'Премахване на фон'},{href:'/jpg-to-png',label:'JPG→PNG'}]},
      'meme-generator':{h2a:'Създайте мем безплатно',steps:['Качете или шаблон.','Текст.','Стил.','Изтегляне.'],h2b:"Безплатен генератор на мемета",body:'Мемета в браузъра.',h3why:'Защо?',why:'Най-бързият начин за споделяне.',faqs:[{q:'Качване?',a:'Не.'},{q:'Мое изображение?',a:'Да.'},{q:'Воден знак?',a:'Няма.'},{q:'Слоеве?',a:'Да.'},{q:'Шрифтове?',a:'Impact, Arial Black, Arial, Verdana, Times New Roman, Georgia, Courier New, Comic Sans.'},{q:'PNG?',a:'Да.'}],links:[{href:'/compress',label:'Компресиране'},{href:'/resize',label:'Преоразмеряване'},{href:'/crop',label:'Изрязване'},{href:'/watermark',label:'Воден знак'},{href:'/jpg-to-png',label:'JPG→PNG'}]},
      'jpg-to-svg':{h2a:'JPG в SVG',steps:['<strong>Изображение</strong>.','<strong>Ширина</strong>.','<strong>SVG</strong>.'],h2b:"Безплатен JPG→SVG",body:"<p>Вграждане в SVG.</p>",h3why:'Защо?',why:"Мащабиране без загуба.",faqs:[{q:'Векторизация?',a:'Не — обвивка.'},{q:'Запазване?',a:'Не.'}],links:[{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/image-to-ico',label:'В ICO'},{href:'/compress',label:'Компресиране'},{href:'/resize',label:'Преоразмеряване'}]},
      'html-to-image':{h2a:'Уебсайт в изображение',steps:['<strong>URL</strong>.','<strong>Настройки</strong>.','<strong>Заснемане</strong>.','<strong>Изтегляне</strong>.'],h2b:'Безплатно заснемане на уеб',body:'<p>Заснемане на уебстраници.</p>',h3why:'Защо?',why:'Документация и архивиране.',faqs:[{q:'URL?',a:'Публични страници.'},{q:'Размери?',a:'Мобилен, Таблет, Десктоп, Full HD.'},{q:'Формати?',a:'JPG, PNG.'},{q:'Безплатно?',a:'Да.'},{q:'Мобилен?',a:'Да — 375px.'}],links:[{href:'/compress',label:'Компресиране'},{href:'/resize',label:'Преоразмеряване'},{href:'/jpg-to-png',label:'JPG→PNG'},{href:'/crop',label:'Изрязване'},{href:'/watermark',label:'Воден знак'}]},
    },
    about:{title:'За нас — RelahConvert',hero_h1_1:'За',hero_h1_em:'RelahConvert',hero_p:'Безплатни инструменти.',s1_h:'Кои сме ние',s1_p1:'Безплатни инструменти в браузъра.',s1_p2:'Вашите файлове са ваши.',s2_h:'Мисия',s2_p:'Професионални инструменти за всички.',s3_h:'Защо RelahConvert?',s3_f1:'100% безплатно',s3_f2:'На вашето устройство',s3_f3:'Без реклами',s3_f4:'Всеки модерен браузър'},
    contact:{title:'Контакт — RelahConvert',hero_h1_1:'Свържете',hero_h1_em:'се с нас',hero_p:'Въпрос или бъг?',s1_h:'Контакт',s1_p:'Отговор до 1–2 дни.',s2_h:'Какво да включите',s2_p1:'Кажете ни:',s2_p2:'• Инструмент<br>• Описание<br>• Браузър'},
    privacy:{title:'Поверителност — RelahConvert',hero_h1_1:'Политика за',hero_h1_em:'поверителност',updated:'Март 2026',s1_h:'Без качване',s1_p:'Обработка локално в браузъра. Изключение: HTML в изображение изпраща URL към трета страна.',s2_h:'Данни',s2_p1:'Анонимни данни.',s2_p2:'Без лични данни.',s3_h:'Бисквитки',s3_p:'Само необходими. Вижте <a href="/cookies">Политика</a>.',s4_h:'Трети страни',s4_p:'Не продаваме данни.'},
    terms:{title:'Условия — RelahConvert',hero_h1_1:'Условия за',hero_h1_em:'ползване',updated:'Март 2026',s1_h:'Ползване',s1_p:'Безплатно.',s2_h:'Гаранция',s2_p:'Няма.',s3_h:'Отговорност',s3_p:'Ограничена.',s4_h:'Собственост',s4_p:'Наша.',s5_h:'Промени',s5_p:'Може да актуализираме.'},
    cookies:{title:'Бисквитки — RelahConvert',hero_h1_1:'Политика за',hero_h1_em:'бисквитки',updated:'Март 2026',s1_h:'Какво са',s1_p:'Текстови файлове.',s2_h:'Ползване',s2_p:'Само необходими.',s3_h:'Трети страни',s3_p:'Няма.',s4_h:'Управление',s4_p:'Деактивирайте в браузъра.'},
  },`,
};

// The script will be continued in part 2 - this file is getting too large for a single write
// Let's write it as a runnable script that reads the file, finds the insertion point, and inserts all languages

// Find insertion point: the line "}\n\nexport function getLang"
const insertMarker = '}\n\nexport function getLang';
const insertPos = content.indexOf(insertMarker);

if (insertPos === -1) {
  console.error('Could not find insertion marker');
  process.exit(1);
}

// Build all language blocks
const allBlocks = Object.values(langs).join('\n');

// Insert before the closing } of translations object
// insertPos points to the } in "}\n\nexport function getLang"
// We want to add new blocks before that }
content = content.slice(0, insertPos) + allBlocks + '\n' + content.slice(insertPos);

fs.writeFileSync(filePath, content, 'utf8');
console.log('Phase 1 done: zh, zh-TW, bg inserted');
console.log('File size:', content.length, 'bytes');
